// This file generated by ngrestcg
// For more information, please visit: https://github.com/loentar/ngrest

#ifndef TICTACSERVER_H
#define TICTACSERVER_H

#include <ngrest/common/Service.h>
#include <unordered_map>
#include <vector>
#include <utility>
//! Dummy description for the service
/*! Some detailed description of the service */
// '*location' comment sets resource path for this service
// *location: tictacserver
class tictacserver: public ngrest::Service
{
public:


    // *method: GET
    // *location: /getplayerinfo
    std::unordered_map<int,int> GetPlayerInfo();

    // *method: GET
    // *location: /getallgames
    std::unordered_map<int, std::vector<std::vector<char>> > GetAllGames();

    // *method: GET
    // *location: /getallgamesstatus
    std::unordered_map<int, std::vector<int>> GetAllGamesStatus();

    // *method: POST
    // *location: /newplayer
    int create_new_player();

    // *method: POST
    // *location: /createnewgame
    std::string create_new_game();

    // *method: POST
    // *location: /makeamove/{gameid}/{playerid}/{row}/{col}
    std::string move(int gameid,int playerid,int row,int col);
};


#endif // TICTACSERVER_H



